/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
//import clases.Avion;

import clases.Avion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.AdminSerializacion;

/**
 *
 * @author angel
 */
public class frmAvion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAvion
     */
    private boolean _agregando;
    private int _indiceSeleccionado;
    public frmAvion() {
        initComponents();
        actualizarElementosTabla();
    }
    /**
     * Actualiza los elementos de la tabla
     */
    public void actualizarElementosTabla(){
        String[] titulos={"Codigo","Aerolinea","Numero de Asientos"};
        DefaultTableModel df=new DefaultTableModel(MDIPrincipal.gAvion.getArrayModel(),titulos);
        this.jtAviones.setModel(df);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtArolinea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumAsientos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnNuevoAvion1 = new javax.swing.JButton();
        btnEditarAvion1 = new javax.swing.JButton();
        btnGuardarAvion1 = new javax.swing.JButton();
        btnEliminarAvion1 = new javax.swing.JButton();
        btnBuscarAvion1 = new javax.swing.JButton();
        btnSalirformAvion1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAviones = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Código");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Aerolinea");

        txtArolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArolineaActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Asientos");

        txtNumAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAsientosActionPerformed(evt);
            }
        });

        jLabel6.setText("REGISTRO DE AVIONES");

        btnNuevoAvion1.setText("Nuevo");
        btnNuevoAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAvion1ActionPerformed(evt);
            }
        });

        btnEditarAvion1.setText("Editar");
        btnEditarAvion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarAvion1MousePressed(evt);
            }
        });
        btnEditarAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAvion1ActionPerformed(evt);
            }
        });

        btnGuardarAvion1.setText("Guardar ");
        btnGuardarAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAvion1ActionPerformed(evt);
            }
        });

        btnEliminarAvion1.setText("Eliminar");
        btnEliminarAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAvion1ActionPerformed(evt);
            }
        });

        btnBuscarAvion1.setText("Buscar");
        btnBuscarAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAvion1ActionPerformed(evt);
            }
        });

        btnSalirformAvion1.setText("Salir");
        btnSalirformAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirformAvion1ActionPerformed(evt);
            }
        });

        jtAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jtAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtAvionesMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jtAviones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtArolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoAvion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarAvion1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btnGuardarAvion1)
                                .addGap(12, 12, 12)
                                .addComponent(btnEliminarAvion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarAvion1)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalirformAvion1)
                        .addGap(104, 104, 104)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoAvion1)
                    .addComponent(btnEditarAvion1)
                    .addComponent(btnGuardarAvion1)
                    .addComponent(btnBuscarAvion1)
                    .addComponent(btnEliminarAvion1)
                    .addComponent(btnSalirformAvion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArolineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArolineaActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNumAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAsientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAsientosActionPerformed

    private void btnNuevoAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAvion1ActionPerformed
        // TODO add your handling code here:
         this._agregando=true;

    }//GEN-LAST:event_btnNuevoAvion1ActionPerformed

    private void btnEditarAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAvion1ActionPerformed
        // TODO add your handling code here:
        this._agregando=false;
        this.txtCodigo.setEditable(false);
        /**
        frmVuelo frmAv= new frmVuelo();
        this.desktopPane.add(frmAv);
        frmAv.setVisible(true);
        this._agregando=false;
        */
    }//GEN-LAST:event_btnEditarAvion1ActionPerformed

    private void btnGuardarAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAvion1ActionPerformed
        // TODO add your handling code here:
        String codigo,aerolinea,numAsientos;
        int numAsB,numAsF,numAsC;
        codigo=this.txtCodigo.getText();
        aerolinea=this.txtArolinea.getText();
        numAsientos=this.txtNumAsientos.getText();

        Avion infAv=new Avion();

        infAv.set_codigoAvion(codigo);
        infAv.set_aerolinea(aerolinea);
        infAv.set_numeroAsientos(Integer.parseInt(numAsientos));
        //infAv.agregarAsientosAvion(numAsB, numAsF, numAsC, Integer.parseInt(numAsientos));
        
        System.out.println(infAv);
        
        if(_agregando){
             //pasos para agregar
            /**
            * 1. Solicitar los valores al usuario
            * 2. Crear la instancia
            * 3. setear los valores de la instancia
            * 4. Agregar la instancia de Aeropuerto a la gestion
            * 5. Mostrar los valores
            */

            //MDIPrincipal.gAsientos.agregarAsientosAvion(codigo, numAsB, numAsF, numAsC, 0, MDIPrincipal.gAvion);
            //AdminSerializacion.serializacion(MDIPrincipal.gAvion, "gAvion.obj");
            MDIPrincipal.gAvion.agregarAvion(infAv);
            actualizarElementosTabla();
            AdminSerializacion.serializacion(MDIPrincipal.gAvion, "gAvion.obj");
            //AdminSerializacion.serializacion(MDIPrincipal.gAvion, "gAvion.obj");
            //AdminSerializacion.serializacion(MDIPrincipal.gAvion, "gAsientos.obj");
                    
              
        }else{
            //pasos para Modificar
            /**
             * 1. Solicitar los nuevos valores al usuario 2. Crear la
             * instancia modificada 3. setear los valores de la instancia
             * modificada 4. Modificar la instancia de Aeropuerto a la
             * gestion 5. Mostrar los valores en la tabla
             */
            MDIPrincipal.gAvion.modificarAvion(this._indiceSeleccionado, infAv);
            AdminSerializacion.serializacion(MDIPrincipal.gAvion, "gAvion.obj");
            
        }
        actualizarElementosTabla();
    }//GEN-LAST:event_btnGuardarAvion1ActionPerformed

    private void btnEliminarAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAvion1ActionPerformed
        // TODO add your handling code here:
     
        if(_indiceSeleccionado>=0){
            int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro?", "Warning", JOptionPane.YES_NO_OPTION);
            if(resultado==JOptionPane.YES_NO_OPTION){
               MDIPrincipal.gAvion.eliminarPorIndice(_indiceSeleccionado);
               actualizarElementosTabla();
               AdminSerializacion.serializacion(MDIPrincipal.gAvion, "gAvion.obj");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Favor seleccione el elemento de la tabla que desea eliminar"); 
        }
        
    }//GEN-LAST:event_btnEliminarAvion1ActionPerformed

    private void btnBuscarAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAvion1ActionPerformed
        // TODO add your handling code here:
        String _codigoAvion=JOptionPane.showInputDialog("Ingrese el código de Avion");
        Avion avionEcontr=MDIPrincipal.gAvion.buscarAvionObj(_codigoAvion);
        if(avionEcontr== null){
            JOptionPane.showMessageDialog(this, "Avion no encontrado");
        }else{
            mostrarElemento(avionEcontr);
        }
    }//GEN-LAST:event_btnBuscarAvion1ActionPerformed

    private void btnSalirformAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirformAvion1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirformAvion1ActionPerformed

    private void btnEditarAvion1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarAvion1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEditarAvion1MousePressed

    private void jtAvionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAvionesMousePressed
        // TODO add your handling code here:
        _indiceSeleccionado= this.jtAviones.getSelectedRow();
        if(_indiceSeleccionado!=-1){
            Avion infoAv=MDIPrincipal.gAvion.getAvionByIndex(_indiceSeleccionado);
            mostrarElemento(infoAv);
        }
    }//GEN-LAST:event_jtAvionesMousePressed
    /**
     * MUENTRA LA INFO DEL ELEMENTO SELECCIONADO
     * @param avion OBJETO AVION
     */
    public void mostrarElemento(Avion avion){
        this.txtCodigo.setText(avion.get_codigoAvion());
        this.txtArolinea.setText(avion.get_aerolinea());
        this.txtNumAsientos.setText(Integer.toString(avion.get_numeroAsientos()));
    }

    private javax.swing.JDesktopPane desktopPane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAvion1;
    private javax.swing.JButton btnEditarAvion1;
    private javax.swing.JButton btnEliminarAvion1;
    private javax.swing.JButton btnGuardarAvion1;
    private javax.swing.JButton btnNuevoAvion1;
    private javax.swing.JButton btnSalirformAvion1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jtAviones;
    private javax.swing.JTextField txtArolinea;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumAsientos;
    // End of variables declaration//GEN-END:variables
}
