/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import clases.Cargo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.AdminSerializacion;

/**
 *
 * @author Iveth
 */
public class frmCargo extends javax.swing.JInternalFrame {

      //Atributos 
    private boolean _agregando;
    private int _indiceSeleccion=-1;
    public frmCargo() {
        initComponents();
        this.setTitle("Gestión Cargos");
        try{
            actualizarElementosTabla();
        }catch(Exception e){
        System.out.println("Error al actualizar los elementos"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCargos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Descripcion de Cargo");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo de Cargo");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jtCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtCargosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtCargos);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtDescripcion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this._agregando=true;
        estadoControles(true);
        estadoBotones(false);
        
        this.txtCodigo.setText("");
        this.txtDescripcion.setText("");
      
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this._agregando=false;
        estadoControles(true);
        estadoBotones(false);
        
        this.txtCodigo.setEditable(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
         //pasos 1,2 y 3 son pasos comunes

        //paso 1.
        String codigo, descriciopCargo;
        
         
         codigo=this.txtCodigo.getText();
         descriciopCargo=this.txtDescripcion.getText();
         
        //paso 2.
        Cargo cargo= new Cargo();
        
        
        
        try{
            
            //paso 3.
            cargo.set_codigo(Integer.parseInt(codigo));
            cargo.set_descripcioncargo(descriciopCargo);
            
            

            if (this._agregando) { //Nuevo Aeropuerto

                //pasos para agregar
                /**
                 * 1. Solicitar los valores al usuario 2. Crear la instancia 3.
                 * setear los valores de la instancia 4. Agregar la instancia de
                 * Aeropuerto a la gestion 5. Mostrar los valores
                 */
                
                //paso 4.
                MDIPrincipal.gCargo.agregarCargo(cargo); //Agregando la instancia de Aeropuerto a la gestion, con el metodo de Agregar

            } else {//Editando Aeropuerto

                //pasos para Modificar
                /**
                 * 1. Solicitar los nuevos valores al usuario 2. Crear la
                 * instancia modificada 3. setear los valores de la instancia
                 * modificada 4. Modificar la instancia de Aeropuerto a la
                 * gestion 5. Mostrar los valores en la tabla
                 */
                //paso 4.
                MDIPrincipal.gCargo.modificarCargo(this._indiceSeleccion, cargo);

            }

            //paso 5. tambien es un paso comun para agregar y modificar
            actualizarElementosTabla();
            estadoControles(false);
            estadoBotones(true);

            //PASO 6: Serializar la informacion
            AdminSerializacion.serializacion(MDIPrincipal.gCargo, "gCargo.obj");

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error" +e.getMessage());
        }
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
         String _codigoCargo=JOptionPane.showInputDialog("Ingrese el código de Cargo");
        
        Cargo _cargoEncontrado=MDIPrincipal.gCargo.buscarCargoObj(Integer.parseInt(_codigoCargo));
        if(_cargoEncontrado==null){
            JOptionPane.showMessageDialog(this, "Aeropuerto no encontrado"); 

        }else{
             mostrarElemento(_cargoEncontrado);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jtCargosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCargosMousePressed
        // TODO add your handling code here:
          _indiceSeleccion = this.jtCargos.getSelectedRow();

        if(_indiceSeleccion!= -1){
            Cargo _cargo = MDIPrincipal.gCargo.getCargoByIndex(_indiceSeleccion);
            mostrarElemento(_cargo);
        }
    }//GEN-LAST:event_jtCargosMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if(_indiceSeleccion>=0){
         int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro?", "Warning", JOptionPane.YES_NO_OPTION);
                if(resultado==JOptionPane.YES_OPTION){
                try{
                    MDIPrincipal.gCargo.eliminarPorIndice(_indiceSeleccion);
                    actualizarElementosTabla();
                    //Paso para Serializar informacion
                   AdminSerializacion.serializacion(MDIPrincipal.gCargo, "gCargo.obj");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,"Ha ocurrido un error al eliminar"+e.getMessage());
                }
            }
        }
        else{
           JOptionPane.showMessageDialog(this, "Favor seleccione el elemento de la tabla que desea eliminar"); 
        } 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    //Metodo para configurar la informacion en la tabla
    
            public void actualizarElementosTabla(){
                
                String [] titulos ={"Código","Descripcion Cargo"};
                
                DefaultTableModel dt = new DefaultTableModel(MDIPrincipal.gCargo.getArrayGestion(),titulos);
                
                this.jtCargos.setModel(dt);
           }
            
            
             /**
     * Muestra los elementos en pantalla segun el objeto enviado
     * @param _aeropuerto objeto Aeropuerto
     */
    public void mostrarElemento(Cargo _cargo){
        this.txtCodigo.setText(Integer.toString(_cargo.get_codigo()));
        this.txtDescripcion.setText(_cargo.get_descripcioncargo());
     
    }
    
     public void estadoBotones(boolean _estado){
        this.btnBuscar.setEnabled(_estado);
        this.btnEditar.setEnabled(_estado);
        this.btnEliminar.setEnabled(_estado);
        this.btnGuardar.setEnabled(!_estado);
        this.btnNuevo.setEnabled(_estado);
        
    }
     
       public void estadoControles(boolean _estado){
        this.txtCodigo.setEditable(_estado);
        this.txtDescripcion.setEditable(_estado);
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCargos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
