/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package GUI;
import Gestiones.GestionRuta;
import Gestiones.GestionVuelo;
import clases.Avion;
import clases.Ruta;
import clases.Vuelo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.AdminSerializacion;
/**
 *
 * @author angel
 */
public class frmVuelo extends javax.swing.JInternalFrame {

    /** Creates new form frmVuelo */
    private boolean _agregando=true;
    private boolean _agregandoRuta;
    private int _indiceSeleccionado;
    public frmVuelo() {
        initComponents();
        MDIPrincipal.gAvion.imprimir();
        this.setTitle("Registro de Vuelos");
        try{
            this.CboCodAvRegistroVuelo.setModel(MDIPrincipal.gAvion.getCboModel());
        }catch (Exception e){}
        
    }
    GestionRuta gRutaCache=new GestionRuta();
    //Vuelo gVueloCache=new Vuelo();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtCodRegistroVuelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioRegistroVuelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMonedaRegistroVuelo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtRutasVuelo = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtCodRutRegistroVuelo = new javax.swing.JTextField();
        btnAgregarVuelo = new javax.swing.JToggleButton();
        CboCodAvRegistroVuelo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnEliminarRutVuelo = new javax.swing.JButton();
        btnNuevoRutVuelo = new javax.swing.JButton();
        btnGuardarRutVuelo = new javax.swing.JButton();
        btnNuevoVuelo = new javax.swing.JButton();
        btnBuscarVuelo = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("REGISTRO DE VUELO");

        jLabel2.setText("REGISTRO DE VUELO");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Código");

        txtCodRegistroVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRegistroVueloActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio");

        jLabel11.setText("Moneda");

        txtMonedaRegistroVuelo.setText("$, L, etc. ");
        txtMonedaRegistroVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonedaRegistroVueloActionPerformed(evt);
            }
        });

        jtRutasVuelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aeropuerto Origen", "Pais Origen", "Ciudad Origen", "Fecha Salida", "Hora Salida", "Pais Destino", "Aeropuerto Destino", "Ciudad Destino", "Fecha Llegada", "Hora Llegada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtRutasVuelo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jtRutasVueloComponentAdded(evt);
            }
        });
        jtRutasVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtRutasVueloMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jtRutasVuelo);

        jLabel12.setText("INGRESO DE LAS RUTAS DE VUELO");

        jLabel14.setText("Código de Ruta");

        txtCodRutRegistroVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRutRegistroVueloActionPerformed(evt);
            }
        });

        btnAgregarVuelo.setText("AGREGAR VUELO");
        btnAgregarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVueloActionPerformed(evt);
            }
        });

        CboCodAvRegistroVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboCodAvRegistroVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboCodAvRegistroVueloActionPerformed(evt);
            }
        });

        jLabel10.setText("Codigo de Avion");

        btnEliminarRutVuelo.setText("Eliminar");
        btnEliminarRutVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRutVueloActionPerformed(evt);
            }
        });

        btnNuevoRutVuelo.setText("Nueva Ruta");
        btnNuevoRutVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRutVueloActionPerformed(evt);
            }
        });

        btnGuardarRutVuelo.setText("Guardar");
        btnGuardarRutVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRutVueloActionPerformed(evt);
            }
        });

        btnNuevoVuelo.setText("NUEVO VUELO");
        btnNuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVueloActionPerformed(evt);
            }
        });

        btnBuscarVuelo.setText("BUSCAR UN VUELO");
        btnBuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 630, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(517, 517, 517))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(122, 122, 122)
                                                        .addComponent(jLabel12)
                                                        .addGap(133, 133, 133)
                                                        .addComponent(jLabel14)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtCodRutRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCodRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMonedaRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPrecioRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addGap(28, 28, 28)
                                                .addComponent(CboCodAvRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(118, 118, 118))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(btnNuevoRutVuelo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnGuardarRutVuelo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminarRutVuelo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(567, 567, 567)
                                        .addComponent(btnAgregarVuelo)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNuevoVuelo)
                .addGap(36, 36, 36)
                .addComponent(btnBuscarVuelo)
                .addGap(526, 526, 526))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 644, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 644, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCodRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtMonedaRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CboCodAvRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8)
                        .addComponent(txtPrecioRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(txtCodRutRegistroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoRutVuelo)
                    .addComponent(btnGuardarRutVuelo)
                    .addComponent(btnEliminarRutVuelo))
                .addGap(54, 54, 54)
                .addComponent(btnAgregarVuelo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarVuelo)
                    .addComponent(btnNuevoVuelo))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 319, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 319, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Actualiza los elementos de la tabla Rtas de Vuelo
     */
    public void actualizarElementosTablaRutas(){
        String[] titulos={"Aropuerto Origen","Pais Origen","Ciudad Origen","Fecha Salida","Aropuerto Destino","Pais Destino","Ciudad Destino","Fecha Llegada"};
        DefaultTableModel df=new DefaultTableModel(gRutaCache.getArrayModel(),titulos);
        this.jtRutasVuelo.setModel(df);
    }
    private void txtMonedaRegistroVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonedaRegistroVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonedaRegistroVueloActionPerformed

    private void jtRutasVueloComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jtRutasVueloComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRutasVueloComponentAdded

    private void txtCodRutRegistroVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRutRegistroVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRutRegistroVueloActionPerformed

    private void CboCodAvRegistroVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboCodAvRegistroVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboCodAvRegistroVueloActionPerformed

    private void btnNuevoRutVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRutVueloActionPerformed
        // TODO add your handling code here:
        this._agregandoRuta=true;
        //this.txtCodRegistroVuelo.setText("Hola");
        
    }//GEN-LAST:event_btnNuevoRutVueloActionPerformed

    private void btnGuardarRutVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRutVueloActionPerformed
        // TODO add your handling code here:
        if(_agregandoRuta){
            String codigoRuta=this.txtCodRutRegistroVuelo.getText();
            Ruta infoRuta=new Ruta();
            infoRuta = MDIPrincipal.gRuta.buscarRutaObj(codigoRuta);
            gRutaCache.agregarRuta(infoRuta);
            actualizarElementosTablaRutas();
            this._agregandoRuta=false;
        }
        
    }//GEN-LAST:event_btnGuardarRutVueloActionPerformed

    private void btnEliminarRutVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRutVueloActionPerformed
        // TODO add your handling code here:
         if(_indiceSeleccionado>=0){
            int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro?", "Warning", JOptionPane.YES_NO_OPTION);
            if(resultado==JOptionPane.YES_NO_OPTION){
               gRutaCache.eliminarRutaPorIndice(_indiceSeleccionado);
               actualizarElementosTablaRutas();
               AdminSerializacion.serializacion(MDIPrincipal.gRuta, "gRuta.obj");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Favor seleccione el elemento de la tabla que desea eliminar"); 
        }       
    }//GEN-LAST:event_btnEliminarRutVueloActionPerformed

    private void txtCodRegistroVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRegistroVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRegistroVueloActionPerformed

    private void btnAgregarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVueloActionPerformed
        // TODO add your handling code here:
                             //pasos para agregar
            /**
            * 1. Solicitar los valores al usuario
            * 2. Crear la instancia
            * 3. setear los valores de la instancia
            * 4. Agregar la instancia de Aeropuerto a la gestion
            * 5. Mostrar los valores
            */
            if (_agregando){
                String codigo,moneda;
                double precio;
                codigo=this.txtCodRegistroVuelo.getText();
                precio=Double.parseDouble(this.txtPrecioRegistroVuelo.getText());
                moneda=this.txtMonedaRegistroVuelo.getText();

                Vuelo infoVuelo=new Vuelo();
                infoVuelo.set_codigoVuelo(codigo);
                infoVuelo.set_moneda(moneda);
                infoVuelo.set_precioVuelo(precio);
                
                Avion infoAvion=MDIPrincipal.gAvion.buscarAvionObj(this.CboCodAvRegistroVuelo.getItemAt(this.CboCodAvRegistroVuelo.getSelectedIndex())); //poner el metodo correncto en getItem..
                
                infoVuelo.set_avion(infoAvion);
                //infoVuelo.listRutas.remove();
                //
                for(int i=0;i<gRutaCache.getListarutas().size(); i++){
                    infoVuelo.agregarRuta(gRutaCache.getListarutas().get(i));
                }
                //infoVuelo.listRutas=gRutaCache.getListarutas(); 
                MDIPrincipal.gVuelo.agregarVuelo(infoVuelo);
                //System.out.println(gRutaCache.toString());
                gRutaCache.eliminarRutas();
                AdminSerializacion.serializacion(MDIPrincipal.gVuelo, "gVuelo.obj");
                //actualizarElementosTablaRutas();
                JOptionPane.showMessageDialog(this, "Vuelo Agregado con Exito");
                this._agregando=false;
                
                
            }
    }//GEN-LAST:event_btnAgregarVueloActionPerformed

    private void btnNuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVueloActionPerformed
        // TODO add your handling code here:
        this._agregando=true;
        this.txtCodRegistroVuelo.setText("");
        this.txtMonedaRegistroVuelo.setText("$,L,etc.");
        this.txtPrecioRegistroVuelo.setText("");
        this.txtCodRutRegistroVuelo.setText("");
        
        DefaultTableModel model = (DefaultTableModel) this.jtRutasVuelo.getModel();
        model.setRowCount(0); 
        gRutaCache.eliminarRutaCache();

        
        
    }//GEN-LAST:event_btnNuevoVueloActionPerformed

    private void btnBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVueloActionPerformed
        // TODO add your handling code here:
        this.getDesktopPane().add(MDIPrincipal.busVuelo);
        MDIPrincipal.busVuelo.setVisible(true);
        
    }//GEN-LAST:event_btnBuscarVueloActionPerformed

    private void jtRutasVueloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtRutasVueloMousePressed
        // TODO add your handling code here:
        _indiceSeleccionado= this.jtRutasVuelo.getSelectedRow();
        if(_indiceSeleccionado!=-1){
           JOptionPane.showMessageDialog(this, "Informacion Seleccionada, Presione el Boton Eliminar"); 
        }
    }//GEN-LAST:event_jtRutasVueloMousePressed

    public void promp(){
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboCodAvRegistroVuelo;
    private javax.swing.JToggleButton btnAgregarVuelo;
    private javax.swing.JButton btnBuscarVuelo;
    private javax.swing.JButton btnEliminarRutVuelo;
    private javax.swing.JButton btnGuardarRutVuelo;
    private javax.swing.JButton btnNuevoRutVuelo;
    private javax.swing.JButton btnNuevoVuelo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable jtRutasVuelo;
    private javax.swing.JTextField txtCodRegistroVuelo;
    private javax.swing.JTextField txtCodRutRegistroVuelo;
    private javax.swing.JTextField txtMonedaRegistroVuelo;
    private javax.swing.JTextField txtPrecioRegistroVuelo;
    // End of variables declaration//GEN-END:variables

}
