/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package GUI;

/**
 *
 * @author Iveth
 */

import Gestiones.*;
import clases.Vuelo;
import java.awt.Dimension;
import util.AdminSerializacion;
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Ubicar todas las gestiones 
     * 
     */
    
    public static GestionAvion gAvion=new GestionAvion();
    public static GestionAeropuerto gAeropuerto = new GestionAeropuerto();
    public static GestionRuta gRuta = new GestionRuta();
    public static GestionEmpleado gEmpleado = new GestionEmpleado();
    public static GestionCargo gCargo = new GestionCargo();
    public static GestionAsientos gAsientos=new GestionAsientos();
    public static GestionVuelo gVuelo=new GestionVuelo();
    public static GestionPasajero gPasajero= new GestionPasajero();
    public static GestionVuelo gCompra= new GestionVuelo();
    
    //public static GestionVuelo gVueloCache=new GestionVuelo();
    public static GestionVuelo gCarrito=new GestionVuelo();
    //public static GestionVuelo gCarrito=new GestionVuelo();
    public static Vuelo gVueloCompra=new Vuelo();
    
    //FORMULARIOS
    public static frmVuelosIngresados busVuelo=new frmVuelosIngresados();
    public static frmCarrito frmInfoCompra=new frmCarrito();
    public static frmIngresoInfoCompra frmIngresoInfoCompra=new frmIngresoInfoCompra();
    public static frmPago frmPago=new frmPago();
    
    public MDIPrincipal() {
        initComponents();
        super.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        //De-Serializacion
        try{
            gAeropuerto  = (GestionAeropuerto ) AdminSerializacion.de_serealizacion("gAeropuerto.obj");
            if(gAeropuerto==null){
                 gAeropuerto = new GestionAeropuerto();
            }
        }catch(Exception e){}
        
        try{
            gRuta = (GestionRuta ) AdminSerializacion.de_serealizacion("gRuta.obj");
            if(gRuta==null){
                 gRuta = new GestionRuta();
            }
        }catch(Exception e){}
        
        try{
            gEmpleado  = (GestionEmpleado ) AdminSerializacion.de_serealizacion("gEmpleado.obj");
            if(gEmpleado==null){
                 gEmpleado = new GestionEmpleado();
            }
        }catch(Exception e){}
        
         try{
            gCargo  = (GestionCargo) AdminSerializacion.de_serealizacion("gCargo.obj");
            if(gCargo==null){
                 gCargo = new GestionCargo();
            }
        }catch(Exception e){}
         
        try{
            gVuelo  = (GestionVuelo) AdminSerializacion.de_serealizacion("gVuelo.obj");
            if(gVuelo==null){
                 gVuelo = new GestionVuelo();
            }
        }catch(Exception e){}    
        
        try{
            gAvion  = (GestionAvion) AdminSerializacion.de_serealizacion("gAvion.obj");
            if(gAvion==null){
                 gAvion = new GestionAvion();
            }
        }catch(Exception e){}  
       
        try{
            gAsientos  = (GestionAsientos) AdminSerializacion.de_serealizacion("gAsientos.obj");
            if(gAsientos==null){
                 gAsientos = new GestionAsientos();
            }
        }catch(Exception e){} 
        
        try{
            gCarrito  = (GestionVuelo) AdminSerializacion.de_serealizacion("gCarrito.obj");
            if(gCarrito==null){
                 gCarrito = new GestionVuelo();
            }
        }catch(Exception e){} 
  
        try{
            gVueloCompra  = (Vuelo) AdminSerializacion.de_serealizacion("gVueloCompra.obj");
            if(gVueloCompra==null){
                 gVueloCompra = new Vuelo();
            }
        }catch(Exception e){}    
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuRuta = new javax.swing.JMenuItem();
        mnuAeropuerto = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuCargos = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        mnuAviones = new javax.swing.JMenuItem();
        mnuVuelos = new javax.swing.JMenuItem();
        mnuVenta = new javax.swing.JMenuItem();
        mnuInfoCompra = new javax.swing.JMenuItem();
        mnuCarrito = new javax.swing.JMenuItem();
        mnuPago = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        mnuRuta.setMnemonic('o');
        mnuRuta.setText("Rutas");
        mnuRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRutaActionPerformed(evt);
            }
        });
        fileMenu.add(mnuRuta);

        mnuAeropuerto.setMnemonic('o');
        mnuAeropuerto.setText("Aeropuertos");
        mnuAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAeropuertoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuAeropuerto);

        mnuEmpleados.setMnemonic('o');
        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        fileMenu.add(mnuEmpleados);

        mnuCargos.setMnemonic('o');
        mnuCargos.setText("Cargos");
        mnuCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargosActionPerformed(evt);
            }
        });
        fileMenu.add(mnuCargos);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mnuAviones.setText("Aviones");
        mnuAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAvionesActionPerformed(evt);
            }
        });
        fileMenu.add(mnuAviones);

        mnuVuelos.setText("Vuelos");
        mnuVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVuelosActionPerformed(evt);
            }
        });
        fileMenu.add(mnuVuelos);

        mnuVenta.setText("Venta");
        mnuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentaActionPerformed(evt);
            }
        });
        fileMenu.add(mnuVenta);

        mnuInfoCompra.setText("InfoCompra");
        mnuInfoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoCompraActionPerformed(evt);
            }
        });
        fileMenu.add(mnuInfoCompra);

        mnuCarrito.setText("Carrito");
        mnuCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarritoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuCarrito);

        mnuPago.setText("Pago");
        mnuPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuPago);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRutaActionPerformed
        // TODO add your handling code here:
        
        frmRuta frmruta = new frmRuta();
        Dimension jInternal=frmruta.getSize(); //Dimension de mi formulario interno
        Dimension desktopSize=this.getSize(); //Dimension de mi desktop
        frmruta.setLocation((desktopSize.width-jInternal.width)/2, (desktopSize.height-jInternal.height)/2);
        this.desktopPane.add(frmruta);
        frmruta.setVisible(true);
        
    }//GEN-LAST:event_mnuRutaActionPerformed

    private void mnuAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAeropuertoActionPerformed
        // TODO add your handling code here:
        
        
        frmAeropuerto frmaero = new frmAeropuerto();
        Dimension jInternal=frmaero.getSize(); //Dimension de mi formulario interno
        Dimension desktopSize=this.getSize(); //Dimension de mi desktop
        frmaero.setLocation((desktopSize.width-jInternal.width)/2, (desktopSize.height-jInternal.height)/2);
        this.desktopPane.add(frmaero);
        frmaero.setVisible(true);
        
    }//GEN-LAST:event_mnuAeropuertoActionPerformed

    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
        // TODO add your handling code here:
        
        frmEmpleado frmempleado = new frmEmpleado();
        Dimension jInternal=frmempleado.getSize(); //Dimension de mi formulario interno
        Dimension desktopSize=this.getSize(); //Dimension de mi desktop
        frmempleado.setLocation((desktopSize.width-jInternal.width)/2, (desktopSize.height-jInternal.height)/2);
        this.desktopPane.add(frmempleado);
        frmempleado.setVisible(true);
    }//GEN-LAST:event_mnuEmpleadosActionPerformed

    private void mnuCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargosActionPerformed
        // TODO add your handling code here:
        frmCargo frmcargo = new frmCargo();
        Dimension jInternal=frmcargo.getSize(); //Dimension de mi formulario interno
        Dimension desktopSize=this.getSize(); //Dimension de mi desktop
        frmcargo.setLocation((desktopSize.width-jInternal.width)/2, (desktopSize.height-jInternal.height)/2);
        this.desktopPane.add(frmcargo);
        frmcargo.setVisible(true);
        
        
    }//GEN-LAST:event_mnuCargosActionPerformed

    private void mnuAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAvionesActionPerformed
        // TODO add your handling code here:
        frmAvion frmAv= new frmAvion();
        this.desktopPane.add(frmAv);
        frmAv.setVisible(true);
    }//GEN-LAST:event_mnuAvionesActionPerformed

    private void mnuVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVuelosActionPerformed
        // TODO add your handling code here:
        frmVuelo frmVuelo= new frmVuelo();
        this.desktopPane.add(frmVuelo);
        frmVuelo.setVisible(true);
    }//GEN-LAST:event_mnuVuelosActionPerformed

    private void mnuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentaActionPerformed
        // TODO add your handling code here:
        ventaBoletos frmVentaBoletos= new ventaBoletos();
        this.desktopPane.add(frmVentaBoletos);
        frmVentaBoletos.setVisible(true);
    }//GEN-LAST:event_mnuVentaActionPerformed

    private void mnuInfoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoCompraActionPerformed
        // TODO add your handling code here:
        frmIngresoInfoCompra frmVentaBoletos= new frmIngresoInfoCompra();
        this.desktopPane.add(frmVentaBoletos);
        frmVentaBoletos.setVisible(true);
    }//GEN-LAST:event_mnuInfoCompraActionPerformed

    private void mnuCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarritoActionPerformed
        // TODO add your handling code here:
        frmCarrito frmVentaBoletos= new frmCarrito();
        this.desktopPane.add(frmVentaBoletos);
        frmVentaBoletos.setVisible(true);
    }//GEN-LAST:event_mnuCarritoActionPerformed

    private void mnuPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagoActionPerformed
        // TODO add your handling code here:
        frmPago frmVentaBoletos= new frmPago();
        this.desktopPane.add(frmVentaBoletos);
        frmVentaBoletos.setVisible(true);   
        
        
    }//GEN-LAST:event_mnuPagoActionPerformed

    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAeropuerto;
    private javax.swing.JMenuItem mnuAviones;
    private javax.swing.JMenuItem mnuCargos;
    private javax.swing.JMenuItem mnuCarrito;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuInfoCompra;
    private javax.swing.JMenuItem mnuPago;
    private javax.swing.JMenuItem mnuRuta;
    private javax.swing.JMenuItem mnuVenta;
    private javax.swing.JMenuItem mnuVuelos;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
