/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Gestiones.GestionVuelo;
import clases.Vuelo;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.AdminSerializacion;

/**
 *
 * @author angel
 */
public class ventaBoletos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ventaBoletos
     */
    public ventaBoletos() {
        initComponents();
        //System.out.println(MDIPrincipal.gCarrito.toString());
    }
    GestionVuelo gvueloCache = new GestionVuelo();
    private int _indiceSeleccionado;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtFechas = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnBuscVuelos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVuelosDisponibles = new javax.swing.JTable();
        lbCantidadCarrito = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        btnLimpiarVuelos = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("AIRUNAH");

        jLabel2.setText("BIENVENIDO A NUESTRA AROLINEA");

        jLabel3.setText("BUSQUEDA DE VUELO");

        txtOrigen.setText("Ingresa el origen");
        txtOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigenActionPerformed(evt);
            }
        });

        txtDestino.setText("Ingresa el destino");

        txtFechas.setText("Ingresa fechas");
        txtFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechasActionPerformed(evt);
            }
        });

        btnBuscVuelos.setText("Buscar Vuelos");
        btnBuscVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscVuelosActionPerformed(evt);
            }
        });

        jtVuelosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Origen", "Fecha y Hora Salida", "Destino", "Fecha y Hora Llegada", "Escalas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtVuelosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtVuelosDisponiblesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtVuelosDisponibles);

        lbCantidadCarrito.setText("0");

        jLabel5.setText("Vuelos Agregados al Carrito");

        btnCarrito.setText("Ir al Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnLimpiarVuelos.setText("Limpiar");
        btnLimpiarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarVuelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel1))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(878, 878, 878)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscVuelos)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarVuelos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbCantidadCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarrito)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscVuelos)
                            .addComponent(btnLimpiarVuelos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidadCarrito)
                    .addComponent(jLabel5)
                    .addComponent(btnCarrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void actualizarElementosTabla(){
        String[] titulos={"Aropuerto Origen","Ciudad Origen","Pais Origen","Fecha y Hora Salida","Aropuerto Destino","Ciudad Destino","Pais Destino","Fecha y Hora Llegada","Escalas"};
        DefaultTableModel df=new DefaultTableModel(MDIPrincipal.gVuelo.getArrayVuelosClienteModel(),titulos);
        this.jtVuelosDisponibles.setModel(df);
    }
    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    private void txtFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechasActionPerformed

    private void btnBuscVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscVuelosActionPerformed
        // TODO add your handling code here:
        
      try{  
        String origen,destino,fecha;
        origen=this.txtOrigen.getText();
        destino=this.txtDestino.getText();
        fecha=this.txtFechas.getText();
        //GestionVuelo gvueloCache = (GestionVuelo) MDIPrincipal.gVuelo;
        //LinkedList<Vuelo> listVuelosEncotr=new LinkedList<Vuelo>();
        //listVuelosEncotr=MDIPrincipal.gVuelo.buscarVueloCliente(origen, destino, fecha);
        
        MDIPrincipal.gVuelo.buscarVueloCliente(origen, destino, fecha);
        //MDIPrincipal.gVuelo.buscarVueloCliente(origen, destino, fecha);
        gvueloCache = (GestionVuelo) MDIPrincipal.gVuelo;
        //System.out.println(MDIPrincipal.gVuelo.getControlPosiciones().toString());
        actualizarElementosTabla();
        //MDIPrincipal.gVuelo.eliminarControlRuta();
        System.out.println(gvueloCache.toString());
        //AdminSerializacion.serializacion(MDIPrincipal.gVuelo, "gVuelo.obj");
        //DefaultTableModel model = (DefaultTableModel) this.jtVuelosDisponibles.getModel();
        //model.setRowCount(0); 
        //System.out.println(MDIPrincipal.gVuelo.toString()); 
        //MDIPrincipal.gVuelo.eliminarControlRuta();
      }catch(Exception e){} 
        
    }//GEN-LAST:event_btnBuscVuelosActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
        
        this.getDesktopPane().add(MDIPrincipal.frmInfoCompra);
        MDIPrincipal.frmInfoCompra.setVisible(true);
        MDIPrincipal.frmInfoCompra.actualizarElementosTablaCarrito();
        
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnLimpiarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarVuelosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.jtVuelosDisponibles.getModel();
        model.setRowCount(0); 
        gvueloCache.eliminarControlRuta();
        System.out.println(MDIPrincipal.gVuelo.toString()); 
    }//GEN-LAST:event_btnLimpiarVuelosActionPerformed

    private void jtVuelosDisponiblesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVuelosDisponiblesMousePressed
        // TODO add your handling code here:
        _indiceSeleccionado= this.jtVuelosDisponibles.getSelectedRow();
        if(_indiceSeleccionado!=-1){
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea Agregar el Vuelo al Carrito?", "Warning", JOptionPane.YES_NO_OPTION);
            if(resultado==JOptionPane.YES_NO_OPTION){
               MDIPrincipal.gCarrito.agregarcontrolRuta(gvueloCache.getControlPosiciones().get(_indiceSeleccionado));
               this.lbCantidadCarrito.setText(Integer.toString(MDIPrincipal.gCarrito.getControlPosiciones().size()));
               //actualizarElementosTablaRutas();
               AdminSerializacion.serializacion(MDIPrincipal.gCarrito,"gCarrito.obj");
               //System.out.println(MDIPrincipal.gCarrito.getControlPosiciones().size());
               JOptionPane.showMessageDialog(this, "Vuelo Agregado al Carrito");
            } 
        }
    }//GEN-LAST:event_jtVuelosDisponiblesMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscVuelos;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnLimpiarVuelos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jtVuelosDisponibles;
    private javax.swing.JLabel lbCantidadCarrito;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtFechas;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
